app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

$monolog = Log::getMonolog();
$syslog = new \Monolog\Handler\SyslogHandler('papertrail');
$formatter = new \Monolog\Formatter\LineFormatter('%channel%.%level_name%: %message% %extra%');
$syslog->setFormatter($formatter);

$monolog->pushHandler($syslog);


Event::listen('illuminate.query', function($query)
{
    //var_dump($query);
});

Route::get('/', 'HomeController@index');

Route::get('home', 'HomeController@index');

Route::controllers([
	'auth' => 'Auth\AuthController',
	'password' => 'Auth\PasswordController',
]);

Route::resource('youths', 'YouthController');
Route::resource('parents', 'ParentController');
Route::resource('surgeries', 'SurgeryController');

/* Comm */
Route::get('comm', 'CommController@index');
Route::post('comm', 'CommController@storeOptions');
Route::get('comm/recipients', 'CommController@recipients');
Route::post('comm/recipients', 'CommController@storeRecipients');
Route::get('comm/preview', 'CommController@preview');
Route::post('comm/send', 'CommController@send');

Route::get('comm/sms', 'CommController@sms');
Route::get('comm/sms/{sms}', 'CommController@smsView');
Route::get('comm/emails', 'CommController@emails');
Route::get('comm/emails/{emails}', 'CommController@emailView');

Route::get('delivery/sms', 'DeliveryController@sms');
Route::post('delivery/sms', 'DeliveryController@sms');

/* Badges */
Route::get('badges', 'BadgeController@index');
Route::get('badges/youthReport', 'BadgeController@youthReport');
Route::get('badges/youthReport/rerun', 'BadgeController@youthReportRerun');
Route::get('badges/{badges}', 'BadgeController@show');
Route::post('badges/{badges}', 'BadgeController@store');
Route::get('youths/{youths}/badges', 'BadgeController@indexYouthBadges');
Route::get('youths/{youths}/badges/massAssign', 'BadgeController@showYouthBadgesMassAssign');
Route::post('youths/{youths}/badges/massAssign', 'BadgeController@saveYouthBadgesMassAssign');
Route::get('youths/{youths}/badges/{badges}', 'BadgeController@showYouthBadges');
Route::post('youths/{youths}/badges/{badges}', 'BadgeController@storeYouthBadges');

Route::get('reports/verifyDetails', 'ReportController@verifyDetails');

Route::get('me/filter', 'MeController@filter');
Route::patch('me/filter', 'MeController@saveFilter');
Route::delete('me/filter', 'MeController@deleteFilter');
Route::get('me/tfa', 'MeController@getTfa');
Route::post('me/tfa', 'MeController@postTfa');

app/SmsFrom.php
<?php namespace App;

use Illuminate\Database\Eloquent\Model;

class SmsFrom extends Model {

    public function getDescriptorAttribute()
    {
        return $this->attributes['from'] . ' (' . $this->attributes['name'] . ')';
    }

}

app/Http/Controllers/CommController.php
<?php namespace App\Http\Controllers;

use App\Commands\SendEmail;
use App\Commands\SendSms;
use App\Email;
use App\EmailFrom;
use App\Http\Requests;
use App\Http\Controllers\Controller;

use App\Sms;
use App\SmsFrom;
use App\User;
use App\Youth;
use App\YouthParent;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Mail;
use Illuminate\Support\Facades\Queue;
use Illuminate\Support\Facades\Session;

class CommController extends Controller {

    public function __construct()
    {
        $this->middleware('auth');
    }

	public function index()
	{
        //dd(Session::all());
        return view('comm.index', ['modelData' => Session::get('comm_options'),
                                   'attachments' => Session::get('comm_attach'),
                                    'timezoneList' => $this->getTimezones()]);
	}

    public function sms(){
        $smsList = Sms::all();
        return view('comm.smsList', compact('smsList'));
    }

    public function smsView(Sms $sms){
        return view('comm.sms', compact('sms'));
    }

    public function emails(){
        $emailList = Email::all();
        return view('comm.emailList', compact('emailList'));
    }

    public function emailView(Email $email){
        return view('comm.email', compact('email'));
    }

    public function storeOptions(Request $request){
        $this->validate($request, [
            'sms_content' => 'required_if:type.sms,Y|max:459',
            'email_subject' => 'required_if:type.email,Y',
            'email_content' => 'required_if:type.email,Y',
            'type' => 'required',
            'recipient' => 'required',
            'schedule_time' => 'required_if:schedule,Y|date|before:'.date('Y-m-d', strtotime('+2 weeks')). '|after:'.date('Y-m-d'),
        ], [
            'required_if' => 'The :attribute is required.',
        ]);

        Session::put('comm_options', $request->except('_token', 'files'));

        $attach = $this->attachFiles($request);

        if($attach !== true){
            return $attach;
        }

        return redirect('comm/recipients');
    }

    public function recipients(){

        $commOptions = Session::get('comm_options');
        $youths = Youth::whereIn('section_id', array_keys($commOptions['recipient']))->get();
        $adults = User::all();
        $modelData = Session::get('comm_recipients');

        return view('comm.recipients', compact('youths', 'adults', 'modelData'));
    }

    public function storeRecipients(Request $request){
        Session::put('comm_recipients', $request->except('_token'));

        return redirect('comm/preview');
    }

    /**
     * @return \Illuminate\View\View
     */
    public function preview(){
        return view('comm.preview', $this->resolveVars());
    }

    public function send(){
        $commRecipients = $commOptions = $smsFrom = null;
        $emailFrom = $scheduleDate = $attachments = null;
        $emailObj = $smsObj = null;
        extract($this->resolveVars());

        //dd($scheduleDate);

        if (isset($commOptions['type']['email'])) {
            $emailObj = Email::create([
                'email_from_id' => $commOptions['email_from'],
                'user_id' => Auth::id(),
                'subject' => $commOptions['email_subject'],
                'content' => nl2br($commOptions['email_content']),
                'attachments' => serialize($attachments),
                'schedule' => $scheduleDate,
            ]);
        }

        if (isset($commOptions['type']['sms'])) {
            $smsObj = Sms::create([
                'sms_from_id' => $commOptions['sms_from'],
                'user_id' => Auth::id(),
                'content' => $commOptions['sms_content'],
                'schedule' => $scheduleDate,
            ]);
        }



        if(isset($commRecipients['recipient_youth'])) {
            foreach ($commRecipients['recipient_youth'] as $youth) {
                if (isset($commOptions['type']['email'])) {
                    Queue::later($scheduleDate, new SendEmail(['id' => $emailObj->id, 'youth_id' => $youth->id]));
                    $emailObj->youths()->attach([$youth->id => ['status' => 'Queued']]);

                    foreach($youth->parents as $parent){
                        Queue::later($scheduleDate, new SendEmail(['id' => $emailObj->id, 'youth_parent_id' => $parent->id]));
                        $emailObj->parents()->attach([$parent->id => ['status' => 'Queued']]);
                    }
                }

                if (isset($commOptions['type']['sms'])) {
                    Queue::later($scheduleDate, new SendSms(['id' => $smsObj->id, 'youth_id' => $youth->id]));
                    $smsObj->youths()->attach([$youth->id => ['status' => 'Queued']]);

                    foreach($youth->parents as $parent){
                        Queue::later($scheduleDate, new SendSms(['id' => $smsObj->id, 'youth_parent_id' => $parent->id]));
                        $smsObj->parents()->attach([$parent->id => ['status' => 'Queued']]);
                    }
                }
            }
        }

        if(isset($commRecipients['recipient_adult'])) {
            foreach ($commRecipients['recipient_adult'] as $user) {
                if (isset($commOptions['type']['email'])) {
                    Queue::later($scheduleDate, new SendEmail(['id' => $emailObj->id, 'user_id' => $user->id]));
                    $emailObj->users()->attach([$user->id => ['status' => 'Queued']]);
                }

                if (isset($commOptions['type']['sms'])) {
                    Queue::later($scheduleDate, new SendSms(['id' => $smsObj->id, 'user_id' => $user->id]));
                    $smsObj->users()->attach([$user->id => ['status' => 'Queued']]);
                }
            }
        }

        $this->clearSession();

        \Flash::success('That message has been queued to send!');

        return redirect('comm');
    }

    private function attachFiles($request){
        $filesToAttach = Session::get('comm_attach');

        if(is_null($filesToAttach)){
            $filesToAttach = [];
        }

        $uploadErrorMessages = [];
        $destPath = 'uploads';

        foreach($request->all()['files'] as $file){
            if(is_null($file)) continue;

            $fileName = trim($file->getClientOriginalName());

            if($file->isValid()){
                if($file->move($destPath, $fileName)) {
                    $filesToAttach[] = $fileName;
                }else{
                    $uploadErrorMessages[] = 'Unable to upload ' . $fileName;
                }
            }else{
                $uploadErrorMessages[] = 'File is invalid: ' . $fileName;
            }
        }

        Session::put('comm_attach', $filesToAttach);

        //dd(Session::all());

        if(count($uploadErrorMessages) > 0){
            \Flash::message(join(', ', $uploadErrorMessages));
            return redirect('comm');
        }

        return true;
    }

    private function resolveVars(){
        $smsFrom = $emailFrom = null;
        $commOptions = Session::get('comm_options');
        $commRecipients = Session::get('comm_recipients');
        $attachments = Session::get('comm_attach');

        if(isset($commRecipients['recipient_youth'])) {
            $commRecipients['recipient_youth'] = Youth::whereIn('id', array_keys($commRecipients['recipient_youth']))->get();
        }

        if(isset($commRecipients['recipient_adult'])) {
            $commRecipients['recipient_adult'] = User::whereIn('id', array_keys($commRecipients['recipient_adult']))->get();
        }

        if(isset($commOptions['type']['sms'])) {
            $smsFrom = SmsFrom::find($commOptions['sms_from']);
        }

        if(isset($commOptions['type']['email'])) {
            $emailFrom = EmailFrom::find($commOptions['email_from']);
        }

        if(isset($commOptions['schedule']) && $commOptions['schedule'] == 'Y'){
            $scheduleDate = Carbon::parse($commOptions['schedule_time'], $commOptions['schedule_timezone']);

        }else{
            $scheduleDate = Carbon::now();
        }

        if(isset($commOptions['schedule_timezone'])){
            $scheduleTimezone = $commOptions['schedule_timezone'];
        }

        return compact('commOptions', 'commRecipients', 'smsFrom', 'emailFrom', 'scheduleDate', 'scheduleTimezone', 'attachments');
    }

    private function clearSession()
    {
        Session::forget('comm_options');
        Session::forget('comm_recipients');
        Session::forget('comm_attach');
    }

    function getTimezones(){
        $zones = timezone_identifiers_list();
        $locations = array();

        foreach ($zones as $zone)
        {
            $locations[$zone] = str_replace('_', ' ', $zone);
        }

        return $locations;
    }

}

resources/views/comm/email.blade.php
@extends('app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-10 col-md-offset-1">
                <div class="panel panel-default">
                    <div class="panel-heading ">View Email</div>

                    <div class="panel-body">

                        <div class="row">

                            <div class="col-md-6">
                                <table class="table">
                                    <tbody>
                                        <tr><td><strong>From</strong>:</td><td>{{ $email->sender->descriptor }}</td></tr>
                                        <tr><td><strong>Subject</strong>:</td><td>{{ $email->subject }}</td></tr>
                                        <tr><td><strong>Attachments</strong>:</td><td>
                                            @if(count(unserialize($email->attachments)) == 0)
                                                None
                                            @else
                                                @foreach(unserialize($email->attachments) as $attachment)
                                                    {{ $attachment }} <br />
                                                @endforeach
                                            @endif
                                        </td></tr>
                                        <tr><td><strong>Content</strong>:</td><td>{{ nl2br($email->content) }}</td></tr>
                                    </tbody>
                                </table>

                                <div class="panel panel-default">
                                    <div class="panel-heading">
                                        <h3 class="panel-title">Youth Recipients</h3>
                                    </div>
                                    <div class="panel-body">
                                        @if(count($email->youths) == 0)
                                            None
                                        @else
                                        <table class="table table-striped table-hover">
                                            <thead>
                                            <tr>
                                                <th>Who</th>
                                                <th>Status</th>
                                                <th>Last Update</th>
                                            </tr>
                                            </thead>
                                            <tbody>
                                            @foreach($email->youths as $youth)
                                                <tr>
                                                    <td>{{ $youth->name }}</td>
                                                    <td>{{ $youth->pivot->status }}</td>
                                                    <td><abbr title="{{ $youth->pivot->updated_at }}">{{ $youth->pivot->updated_at->diffForHumans() }}</abbr></td>
                                                </tr>
                                            @endforeach
                                            </tbody>
                                        </table>
                                        @endif
                                    </div>
                                </div>

                                <div class="panel panel-default">
                                    <div class="panel-heading">
                                        <h3 class="panel-title">Leader Recipients</h3>
                                    </div>
                                    <div class="panel-body">
                                        @if(count($email->users) == 0)
                                            None
                                        @else
                                        <table class="table">
                                            <thead>
                                            <tr>
                                                <th>Who</th>
                                                <th>Status</th>
                                                <th>Last Update</th>
                                            </tr>
                                            </thead>
                                            <tbody>
                                            @foreach($email->users as $user)
                                                <tr>
                                                    <td>{{ $user->name }}</td>
                                                    <td>{{ $user->pivot->status }}</td>
                                                    <td><abbr title="{{ $user->pivot->updated_at }}">{{ $user->pivot->updated_at->diffForHumans() }}</abbr></td>
                                                </tr>
                                            @endforeach
                                            </tbody>
                                        </table>
                                        @endif
                                    </div>
                                </div>

                            </div>


                            <div class="col-md-6">

                                <div class="panel panel-default">
                                    <div class="panel-heading">
                                        <h3 class="panel-title">Parent Recipients</h3>
                                    </div>
                                    <div class="panel-body">
                                        @if(count($email->parents) == 0)
                                            None
                                        @else
                                        <table class="table">
                                            <thead>
                                            <tr>
                                                <th>Who</th>
                                                <th>Status</th>
                                                <th>Last Update</th>
                                            </tr>
                                            </thead>
                                            <tbody>
                                            @foreach($email->parents as $parent)
                                                <tr>
                                                    <td>{{ $parent->name }}</td>
                                                    <td>{{ $parent->pivot->status }}</td>
                                                    <td><abbr title="{{ $parent->pivot->updated_at }}">{{ $parent->pivot->updated_at->diffForHumans() }}</abbr></td>
                                                </tr>
                                            @endforeach
                                            </tbody>
                                        </table>
                                        @endif
                                    </div>
                                </div>




                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/comm/emailList.blade.php
@extends('app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-10 col-md-offset-1">
                <div class="panel panel-default">
                    <div class="panel-heading ">Communication - Sent Emails</div>


                    <div class="panel-body">
                        <a href="{{ url('/comm') }}" class="btn btn-primary pull-right">Create</a>
                        <table class="table table-striped table-hover">
                            <thead>
                            <tr>
                                <th>Email</th>
                                <th>Sent</th>
                                <th></th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($emailList as $email)
                                <tr>
                                    <td>{{ str_limit($email->content, 150) }}</td>
                                    <td>{{ $email->created_at }}</td>
                                    <td>
                                        <div class="btn-toolbar" role="toolbar">
                                            <div class="btn-group">
                                                <a href="{{ url('/comm/emails/' . $email->id) }}" class="btn btn-default btn-xs" aria-label="View"><span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span></a>
                                            </div>
                                        </div>
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/comm/index.blade.php
@extends('app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-10 col-md-offset-1">
                <div class="panel panel-default">
                    <div class="panel-heading ">Communicate</div>


                    <div class="panel-body">

                        {!! Form::model($modelData, ['url' => 'comm', 'files'=>true]) !!}
                            @include('comm.form')
                        {!! Form::close() !!}

                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/comm/preview.blade.php
@extends('app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-10 col-md-offset-1">
                <div class="panel panel-default">
                    <div class="panel-heading ">Communicate</div>

                    {!! Form::open(['url' => 'comm/send']) !!}

                    <div class="panel-body">

                        <p>This is the preview screen, so you can review the message you are preparing to send out.
                            Feel free to use the back buttons to edit anything you see is wrong.
                            Email address or phone numbers will be highlighted in red if the system thinks they are invalid,
                            and it will not send to these recipients for that type of message.</p>

                        <div class="row">
                            <div class="col-md-6">

                                @if(isset($commOptions['type']['email']))

                                    <div class="panel panel-default">
                                        <div class="panel-heading">
                                            <h3 class="panel-title">Email Preview</h3>
                                        </div>
                                        <div class="panel-body">

                                            <strong>From:</strong> {{ $emailFrom->descriptor }}<br />
                                            <strong>To:</strong>
                                            @if(isset($commRecipients['recipient_youth']))
                                                @foreach($commRecipients['recipient_youth'] as $youth)
                                                    {{ $youth->name }} <small>({{ $youth->email }})</small> <br />
                                                @endforeach
                                            @endif

                                            @if(isset($commRecipients['recipient_adult']))
                                                <br />
                                                @foreach($commRecipients['recipient_adult'] as $user)
                                                    {{ $user->name }} <small>({{ $user->email }})</small> <br />
                                                @endforeach
                                            @endif
                                            <br />
                                            <strong>Subject:</strong> {{ $commOptions['email_subject'] }}<br />
                                            <strong>Attachments:</strong>
                                            @if(count($attachments) > 0)
                                                <br/>
                                                @foreach($attachments as $attachment)
                                                    {{ $attachment }}<br/>
                                                @endforeach
                                            @else
                                                None
                                            @endif
                                            <br />
                                            <strong>Message</strong><br /><br />
                                            {!! nl2br($commOptions['email_content']) !!}

                                        </div>
                                    </div>

                                    @if(env('MAIL_HOST') == 'mailtrap.io')
                                        <div class="alert alert-danger">
                                            <strong>Email test mode is enabled.</strong>
                                            <p>The emails will not get sent.<br/>Please inform a System Administrator.</p>
                                        </div>
                                    @endif

                                @endif


                            </div>


                            <div class="col-md-6">

                                @if(isset($commOptions['type']['sms']))

                                    <div class="panel panel-default">
                                        <div class="panel-heading">
                                            <h3 class="panel-title">Text Message Preview</h3>
                                        </div>
                                        <div class="panel-body">

                                            <strong>From:</strong> {{ $smsFrom->descriptor }}<br />
                                            <strong>To:</strong>
                                            @if(isset($commRecipients['recipient_youth']))
                                                @foreach($commRecipients['recipient_youth'] as $youth)
                                                    @if($youth->validMobile)
                                                        {{ $youth->name }} <small>({{ $youth->telephone }})</small>
                                                    @else
                                                        <span style="color:red;">{{ $youth->name }} <small>({{ $youth->telephone }})</small></span>
                                                    @endif

                                                    <br />
                                                @endforeach
                                            @endif

                                            @if(isset($commRecipients['recipient_adult']))
                                                <br />
                                                @foreach($commRecipients['recipient_adult'] as $user)
                                                    {{ $user->name }} <small>({{ $user->telephone }})</small> <br />
                                                @endforeach
                                            @endif
                                            <br />
                                            <strong>Message</strong><br /><br />
                                            {{ $commOptions['sms_content'] }}

                                        </div>
                                    </div>

                                    @if(env('TEXTLOCAL_TEST', 'true') == 'true')
                                        <div class="alert alert-danger">
                                            <strong>TextLocal test mode is enabled.</strong>
                                            <p>These text messages will not get sent.<br/>Please inform a System Administrator.</p>
                                        </div>
                                    @endif

                                @endif

                                @if(isset($commOptions['schedule']) && $commOptions['schedule'] == 'Y')
                                    <div class="alert alert-warning">
                                        <strong>This message is scheduled!</strong>
                                        <p>It will be sent out at around {{ $scheduleDate }}</p>

                                    </div>
                                @endif





                                <button type="submit" class="btn btn-primary form-control">Send!</button>
                            </div>




                        </div>

                    </div>

                    {!! Form::close() !!}

                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/comm/smsList.blade.php
@extends('app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-10 col-md-offset-1">
                <div class="panel panel-default">
                    <div class="panel-heading ">Communication - Sent SMS</div>


                    <div class="panel-body">
                        <a href="{{ url('/comm') }}" class="btn btn-primary pull-right">Create</a>
                        <table class="table table-striped table-hover">
                            <thead>
                            <tr>
                                <th>SMS</th>
                                <th>Sent</th>
                                <th></th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($smsList as $sms)
                                <tr>
                                    <td>{{ $sms->content }}</td>
                                    <td>{{ $sms->created_at }}</td>
                                    <td>
                                        <div class="btn-toolbar" role="toolbar">
                                            <div class="btn-group">
                                                <a href="{{ url('/comm/sms/' . $sms->id) }}" class="btn btn-default btn-xs" aria-label="View"><span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span></a>
                                            </div>
                                        </div>
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection